const initialState = {
  menu: {
    coffeeLatteMenu: [
      {id: 1, name: 'Coffee Latte', price: '$11.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133672.jpg', description: 'A latte or caffè latte is a milk coffee that is a made up of one or two shots of espresso, steamed milk and a final, thin layer of frothed milk on top. If you don\'t drink dairy milk, you can easily swap it for a plant-based alternative like soy, oat or coconut milk.'},
      {id: 2, name: 'Coffee Ice Latte', price: '$15.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133673.jpg', description: 'An iced latte is a drink with espresso, milk and optional sweetener. The milk is often frothed to simulate the steamed milk in a standard latte. So what\'s the difference vs iced coffee? Iced coffee uses brewed coffee and optional milk.'},
      {id: 3, name: 'Coffee Latte Macchiato', price: '$14.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133674.jpg', description: 'The latte macchiato is a sweeter, layered espresso beverage. It is made by adding a shot or half a shot of espresso to steamed milk, topped with a milk foam layer. Unlike an espresso macchiato, which is served in a short glass, a latte macchiato is served in a tall glass. Explore the different coffee cups here.'},
      {id: 4, name: 'Coffee Latte Classic', price: '$13.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133675.jpg', description: 'A caffè latte is simply a shot or two of bold, tasty espresso with fresh, sweet steamed milk over it. Some prefer to add syrup or extra espresso to the recipe.'},
      {id: 5, name: 'Coffee Latte Cinnamon', price: '$16.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133676.jpg', description: 'Cinnamon dolce simply means cinnamon sweet. The latte has a mix of sweetness from the brown sugar and spiciness from the cinnamon.'},
      {id: 6, name: 'Pumpkin-Spiced Coffee Latte', price: '$16.00', img: 'https://www.segodnya.ua/img/forall/users/3241/324106/new/depositphotos_167229816_m-2015.jpg', description: 'At its core, the classic PSL has a good flavor, leaning into the nutmeg, cinnamon and clove notes to execute a long-successful formula.'},
      {id: 7, name: 'Ginger-Gingerbread Coffee Latte', price: '$12.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133677.jpg', description: 'Enjoy the flavors of freshly baked gingerbread with this festive coffee. Aromas of cinnamon and clove and a note of sweetness are blended with our lightest roast coffee for a heartwarming treat.'},
      {id: 8, name: 'Coffee Latte Cheese', price: '$13.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133678.jpg', description: 'Cheese latte is a layer of cream cheese on the top of the latte. It has both a sweet and salty taste of cheese and a delicate latte. This cheese milk lid can be used with a variety of drinks.'},
      {id: 9, name: 'Banana Coffee Latte', price: '$15.00', img: 'https://cdn.goodhouse.com.ua/images-jpg/13367/133679.jpg', description: 'Flavor profile is sweet, creamy, and thick—and although it doesn\'t quite taste like a banana milkshake, it does end up tasting like a more balanced cup of coffee than you\'d usually get with milk alone. The added banana helps cut some of coffee\'s natural acidity, lending itself to a more balanced, mellow drink.'}
    ],
    coffeeMochaMenu: [
      {id: 1, name: 'Iced Caramel Mocha', price: '$11.00', img: 'https://opencart.webdigify.com/OPC04/OPC099_coffee/image/cache/catalog/09-1000x1000.jpg', description: 'Our refreshingly cool iced caramel mocha latte is made with whole milk, chocolate and caramel syrup, and topped with whipped topping and caramel drizzle. There are 280 calories in a small Iced Caramel Mocha Latte with whole milk at McDonald\'s.'},
      {id: 2, name: 'Mocha Frappé', price: '$14.00', img: 'https://opencart.webdigify.com/OPC04/OPC099_coffee/image/cache/catalog/03-1000x1000.jpg', description: 'Made with rich chocolate flavor and a hint of coffee, our Mocha Frappé recipe is blended with ice and topped with whipped light cream and chocolatey drizzle. Available in small, medium and large sizes.'},
      {id: 3, name: 'Mocha', price: '$9.00', img: 'https://images.immediate.co.uk/production/volatile/sites/2/2021/11/Mocha-1fc71f7.png?quality=90&webp=true&resize=600,545', description: 'Although a mocha is often interpreted differently across the world, the basis is that a shot of espresso is combined with a chocolate powder or syrup, followed by milk or cream.'},
      {id: 4, name: 'Mocha porridge', price: '$16.00', img: 'https://images.immediate.co.uk/production/volatile/sites/2/2020/12/Mocha-Porridge-4f26762.jpg?quality=90&webp=true&resize=600,545', description: 'We use maple syrup to sweeten, it adds a lovely caramel flavour perfect with the chocolate and coffee. Useds Caramel Almond Swirl drizzled on top for a sweet, nutty topping, followed by some dark chocolate chips, which melt making the most luxurious mocha porridge\n'},
      {id: 5, name: 'Mocha Latte Recipe', price: '$10.00', img: 'https://www.spoonfulofflavor.com/wp-content/uploads/2021/11/mocha-latte-recipe.jpg', description: 'A mocha latte is simply a coffee latte with the addition of chocolate. The flavors of the coffee and chocolate meld almost seamlessly. You can get that chocolate flavor by adding either cocoa powder or a chocolate syrup.'},
      {id: 6, name: 'Frozen Mocha Frappuccino', price: '$18.00', img: 'https://coffeeatthree.com/wp-content/uploads/starbucks-white-chocolate-mocha-frappuccino-recipe-500x500.jpg', description: 'Is a frozen drink that\'s made in a blender. Ice, whole milk, coffee Frappuccino base syrup, instant coffee, and mocha sauce are blended together then the drink is topped with whipped cream.'}
    ],
    coffeeCappuccinoMenu: [
      {id: 1, name: 'Easy Cappuccino', price: '$15.00', img: 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/exps37407_THE1213734_37407_WEB.jpg', description: 'A cappuccino is the perfect balance of espresso, steamed milk and foam. This coffee is all about the structure and the even splitting of all elements into equal thirds. An expertly made cappuccino should be rich, but not acidic and have a mildly sweet flavouring from the milk.'},
      {id: 2, name: 'Keto Whipped Coffee Cappuccino', price: '$12.00', img: 'https://how2doketo.com/wp-content/uploads/2021/01/Keto-Whipped-Cappuccino-1-500x500.jpg', description: 'Scoop whipped cappuccino cream on top of the warm almond to top with a sprinkle of cinnamon or a sugar-free chocolate shavings for a special treat!'},
      {id: 3, name: 'Cappuccino', price: '$8.00', img: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Cappuccino_at_Sightglass_Coffee.jpg', description: 'A cappuccino is the perfect balance of espresso, steamed milk and foam. This coffee is all about the structure and the even splitting of all elements into equal thirds. An expertly made cappuccino should be rich, but not acidic and have a mildly sweet flavouring from the milk.'},
      {id: 4, name: 'Cappuccino Rapide', price: '$10.00', img: 'https://img.cuisineaz.com/1024x576/2018/12/12/i145259-cappuccino-au-thermomix.jpeg', description: 'Ingredients: A cappuccino features espresso, hot milk, and milk froth, and baristas typically serve drip or pour-over coffee black. As a result of the additional hot milk and milk foam elements.'},
    ],
    greenTeaMenu: [
      {id: 1, name: 'Green Tea', price: '$5.00', img: 'https://static-bebeautiful-in.unileverservices.com/green-tea-youthful-skin-secret_1.jpg', description: 'Green tea, also known as unoxidized tea, is made solely from the leaves of the camellia sinensis plant. The leaves are plucked, slightly withered, then immediately cooked to preserve the green quality and prevent oxidization.'},
      {id: 2, name: 'Cinnamon Green Tea', price: '$5.99', img: 'https://static.toiimg.com/photo/78092190.cms', description: 'The best spices for green tea are fresh ginger, cinnamon, and cardamom. Ginger packs in digestive health benefits and offers a subtle piquant flavor to green teas. A cinnamon stick adds a little sweetness with a spicy kick.\n'},
      {id: 3, name: 'Lemon-Ginger Green Tea', price: '$6.00', img: 'https://www.thespruceeats.com/thmb/bevv5BuE22jGYxztejTzfZ1X7V0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/green-tea-with-lemon-5828c5665f9b58d5b1141810.jpg', description: 'Lemon Green tea has a great zest of lemon coupled with the smooth taste of green tea leaves that give this liquor a full-bodied and wholesome taste. It has a slightly acidic aroma which makes for a perfect morning drink.\n'},
      {id: 4, name: 'Matcha Green Tea', price: '$7.00', img: 'https://images.prom.ua/2538642632_chaj-matcha-latte.jpg', description: 'Matcha is a high-grade green tea ground into powdered form. The green tea powder is whisked into hot water, instead of steeped, to form a frothy drink. The meditative act of preparing, presenting, and sipping matcha.'},
      {id: 5, name: 'Green Tea Infused With Apples & Cinnamon', price: '$7.00', img: 'https://health.clevelandclinic.org/wp-content/uploads/sites/3/2019/02/GreenTeaCinnamonApples-497484228-770x533-1.jpg', description: 'This hot beverage is another brain-healthy choice. On top of that, cinnamon adds not only a flavor boost, but is also loaded with antioxidants. So, go ahead, sit back and sip!'},
    ],
    blackCoffeeMenu: [
      {id: 1, name: 'Black Coffee', price: '$6.00', img: 'https://www.collinsdictionary.com/images/full/blackcoffee_114233497_1000.jpg', description: 'Black coffee is simply coffee with nothing added – no cream, no milk, no sweetener.'},
      {id: 2, name: 'Black Coffee with Milk', price: '$7.99', img: 'https://www.kindpng.com/picc/m/355-3550110_cappuccino-png-coffee-in-white-background-transparent-png.png', description: 'Served in a glass coffee with milk can be made simply by mixing black coffee with about a quarter to half a glass of sweetened condensed milk.'},
      {id: 3, name: 'Iced Coffee', price: '$6.40', img: 'https://cdn.shopify.com/s/files/1/1135/9368/products/GCB_ICED_COFFEE_REDUX_2000x2000.jpg?v=1565306516', description: 'Quite simply, an iced coffee is a cold version of your favourite coffee, but it\'s not simply a coffee that has been left to cool. Like a regular coffee, it\'s usually a combination of hot espresso and milk. However, ice is added too.'},
      {id: 4, name: 'Black Coffee with Whipped Cream', price: '$7.00', img: 'https://coffeeaffection.com/wp-content/uploads/2021/08/a-glass-of-coffee-with-whipped-cream.jpg', description: 'Coffee with whipped cream is such a treat. With a touch of creaminess and sweetness, the flavorful and robust tasting coffee makes for such a nice mouthfeel.'},
    ],
    cupcakeMenu: [
      {id: 1, name: 'Cupcake', price: '$8.00', img: 'https://img.elo7.com.br/product/zoom/24AA24D/cupcake-de-brigadeiro-doces-personalizados.jpg', description: 'A cupcake is a small cake designed to serve one person, which may be baked in a small thin paper or aluminum cup. '},
      {id: 2, name: 'Vanilla Cupcake', price: '$8.99', img: 'https://www.curlyscooking.co.uk/wp-content/uploads/2014/03/Vanilla-Cupcakes-G-scaled.jpg', description: 'Vanilla cupcakes are small cakes that are flavored with vanilla. These cupcakes typically are white or yellow cake.\n'},
      {id: 3, name: 'Chocolate Cupcake', price: '$8.40', img: 'https://handletheheat.com/wp-content/uploads/2016/02/best-chocolate-cupcakes-recipe-SQUARE.jpg', description: 'Chocolate Cupcake is a small cake baked in a small, thin paper cup. It uses cocoa or unsweetened chocolate along with flour as main ingredients and is usually decorated with gorgeous frosting and sprinkles on top.\n'},
      {id: 4, name: 'Strawberry Cupcake', price: '$9.50', img: 'https://static.toiimg.com/thumb/55599531.cms?imgsize=92701&width=800&height=800', description: 'Soft, fluffy, and moist, these fresh Strawberry Cupcakes will melt in your mouth! Easily made from scratch, these cupcakes are filled with fresh strawberries and topped with a beautiful pink strawberry frosting. These cupcakes are bursting with strawberry flavor and are perfect for any occasion.\n'},
      {id: 5, name: '"Galaxy" Cupcake', price: '$10.00', img: 'https://www.frugalmomeh.com/wp-content/uploads/2022/07/Galaxy-Cupcakes-12-scaled-720x540.jpg', description: 'Vanilla cupcakes with a galaxy frosting swirl on top and silver star sprinkles.\n'},
      {id: 6, name: 'Oreo Cupcake', price: '$9.99', img: 'https://www.barleyandsage.com/wp-content/uploads/2022/08/oreo-cupcakes-1200x1200-1.jpg', description: 'Oreo Cupcakes with Cookies & Cream Oreo Frosting are decadent, delicious, and so much fun. These cupcakes are light, airy, and super moist, filled with crumbled chocolate Oreo cookies. With easy-to-make Oreo frosting topped with an Oreo cookie, they look and taste amazing too.\n'},
      {id: 7, name: '"Rainbow" Cupcake', price: '$8.99', img: 'https://i2.wp.com/lifemadesimplebakes.com/wp-content/uploads/2014/02/Rainbow-Cupcakes.jpg', description: 'Rainbow Cupcakes is a dessert that has layers of rainbow cake with vibrant colors topped with a magical cloud of vanilla frosting and rainbow on top.\n'},
    ],
    blackTeaMenu: [
      {id: 1, name: 'Black Tea', price: '$4.00', img: 'https://www.foodandwine.com/thmb/6wTm7a0y87X97LK-ZMxe2787kI8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/different-types-of-tea-FT-BLOG0621-7c7fd231e66d4fea8ca9a47cad52ba79.jpg', description: 'Black tea is a type of tea produced from the camellia sinensis plant that is highly oxidized, resulting in a dark reddish-gold hue, a hearty, slightly astringent flavor, and a moderate amount of caffeine.\n'},
      {id: 2, name: 'Black Tea with Lemon', price: '$4.99', img: 'https://femina.wwmindia.com/thumb/content/2020/jan/weight-loss-01-thumb1579869427.jpg?width=1200&height=900', description: 'Lemon black tea is tea made with black tea leaves and lemon slices. There are many different types and strengths of lemon tea.'},
      {id: 3, name: 'Ginger Lemon Tea', price: '$4.40', img: 'https://www.lifeisbetterwithtea.com/wp-content/uploads/2019/12/ginger_lemon_black_tea-square.jpeg', description: 'Lemon-ginger tea is exactly what it sounds like: a gentle herbal infusion of fresh lemon and ginger — with a bit of sweetener.'},
      {id: 4, name: 'Black Tea with Milk', price: '$5.00', img: 'https://cdn.shopify.com/s/files/1/0241/1927/files/Can_we_add_milk_in_black_tea.png?v=1584466040', description: 'Milk tea, quite simply, is tea with milk added. This creates a smoother flavor and slightly sweetens the tea.'},
      {id: 5, name: 'Black Tea with honey', price: '$5.99', img: 'https://media.istockphoto.com/id/1329550147/photo/herbal-tea.jpg?s=612x612&w=0&k=20&c=nkNIiO4gAhpDVwflAYF-byA3N93pfcG-yVgUvZwHlsA=', description: 'Honey Black Tea has a brown color with a sizable body and enchanting aroma of honey. This tea tastes rich, caramelly, smooth, and brews very well in hot or cold water. The honey like after taste is naturally sweet and long lasting.'},
    ],
    espressoMenu: [
      {id: 1, name: 'Espresso', price: '$5.00', img: 'https://westcupgroup.com/wp-content/uploads/2020/06/1_4FzJWow3qJOV_O-3iKgBOw.jpeg', description: 'As a beverage, espresso is a concentrated form of coffee brewed with high pressure, hot water and finely ground coffee beans. Espresso is thicker than regular coffee and has a layer of “crema” on top, which results from air bubbles mixing with the coffee\'s oils.\n'},
      {id: 2, name: 'Espresso Con Banana', price: '$5.99', img: 'https://st2.depositphotos.com/1202936/7972/i/450/depositphotos_79720672-stock-photo-coffee-vienna.jpg', description: 'Espresso con panna, which means "espresso with cream" a single or double shot of espresso topped with whipped cream.'},
    ],
    hotChocolateMenu: [
      {id: 1, name: 'Hot Chocolate', price: '$6.00', img: 'https://www.foodandwine.com/thmb/V1OEgtLQGUv_w2Fvm40WMLsJ4rk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Indulgent-Hot-Chocolate-FT-RECIPE0223-fd36942ef266417ab40440374fc76a15.jpg', description: 'Hot chocolate, also known as hot cocoa or drinking chocolate, is a heated drink consisting of shaved chocolate, melted chocolate or cocoa powder, heated milk or water.'},
      {id: 2, name: 'Hot Chocolate with Marshmallows', price: '$7.99', img: 'https://www.verywellfit.com/thmb/gqpm--ij8axJC6a2MZ7OLbLSY3Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ExtraDarkHotCocoa_KaleighMcMordie-5a71067beb97de003741b055.jpg', description: 'When it comes to hot chocolate add-ins, nothing beats traditional marshmallows. The lightness created by melting marshmallows or  into hot cocoa to balance the thickness and richness of the chocolate perfectly.\n'},
      {id: 3, name: 'Whipped Hot Chocolate', price: '$7.00', img: 'https://www.julieseatsandtreats.com/wp-content/uploads/2020/12/Whipped-Hot-Chocolate-Recipe-5-of-5.jpg', description: 'When it comes to hot chocolate add-ins it`whipped cream. The lightness and creaminess created by melting whipped cream into hot cocoa to balance the thickness and richness of the chocolate perfectly.\n'},
    ]
  },
  categories: [
    {id: 1, name: 'Coffee Latte', link: '/menu/latte', img: 'https://coffee-point.astemplatedesigns.com/assets/images/Products/Product-4.png'},
    {id: 2, name: 'Cappuccino', link: '/menu/cappuccino', img: 'https://coffee-point.astemplatedesigns.com/assets/images/Products/Product-2.png'},
    {id: 3, name: 'Mocha', link: '/menu/mocha', img: 'https://i0.wp.com/gatherforbread.com/wp-content/uploads/2014/10/Dark-Chocolate-Mocha-Square.jpg?fit=1000%2C1000&ssl=1'},
    {id: 4, name: 'Green Tea',  link: '/menu/green-tea', img: 'https:т//coffee-point.astemplatedesigns.com/assets/images/Products/Product-8.png'},
    {id: 5, name: 'Black Coffee', link: '/menu/black-coffee', img: 'https://healthwire.pk/wp-content/uploads/2022/03/black-coffee-benefits.jpg'},
    {id: 6, name: 'Cupcake', link: '/menu/cupcake', img: 'https://assets-eu-01.kc-usercontent.com/559bb7d3-88a4-01c1-79a3-dd4d5b2d2bb0/18cb6cf1-1105-4cc3-abcf-448435ee9291/Mary%20Berry%20Chocolate%20Cupcakes%20%20(14).jpg?w=3840&q=85&auto=format&lossless=1'},
    {id: 7, name: 'Black Tea',  link: '/menu/black-tea', img: 'https://cdn-prod.medicalnewstoday.com/content/images/articles/319/319646/black-tea.jpg'},
    {id: 8, name: 'Espresso',  link: '/menu/espresso', img: 'https://westcupgroup.com/wp-content/uploads/2020/06/1_4FzJWow3qJOV_O-3iKgBOw.jpeg'},
    {id: 9, name: 'Hot Chocolate', link: '/menu/hot-chocolate', img: 'https://coffee-point.astemplatedesigns.com/assets/images/Products/Product-6.png'},
  ],
}

export const CoffeeMenuReducer = (state = initialState, action: any) => {
  switch (action.type) {
    default:
      return state
  }
}
